name: Deploy to Azure Container App

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag to deploy (e.g., latest or commit SHA)'
        required: true
        default: 'latest'
      environment:
        description: 'Target environment (e.g., staging, production)'
        required: true
        default: 'staging'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container App
        run: |
          az containerapp update \
            --name user-service-${{ github.event.inputs.environment }} \
            --resource-group my-resource-group \
            --image myregistry.azurecr.io/myapp:${{ github.event.inputs.image_tag }}