name: Coverage (after tests)

on:
  workflow_run:
    workflows: [ "Pytest" ]
    types: [ completed ]
    branches: [ main ]

jobs:
  coverage:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 3️⃣ Cache pip dependencies
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 4️⃣ Install dependencies (test + coverage)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt coverage

      # 5️⃣ Run tests with coverage
      - name: Run coverage
        run: coverage run -m pytest

      # 6️⃣ Generate coverage.xml
      - name: Generate coverage XML
        run: coverage xml

      # 7️⃣ Upload artifact
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml