name: Lint (pylint from local image)

on:
  workflow_run:
    workflows: [ "Build Docker Image (Local)" ]
    types: [ completed ]

jobs:
  lint-from-artifact:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Download Docker image artifact
      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: .

      # 2️⃣ Load image into local Docker
      - name: Load Docker image
        run: gunzip -c myapp.tar.gz | docker load

      # 3️⃣ Run pylint inside the container
      #    If pylint isn’t baked in, install before running.
      - name: Run pylint
        run: |
          docker run --rm myapp:ci \
            /bin/sh -lc "python -m pip install --upgrade pip && pip install pylint && pylint your_package_name"