version: '3.8'
services:
  store-service:
    build:
      context: ../store_service
      dockerfile: Dockerfile

    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URI=mysql+pymysql://user:password@mysql-db/store_db
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: store_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: